deploy test

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,3 +1,17 @@
-#!/bin/bash -e
+#!/bin/bash
+echo "Before assembling"
 
-echo "Probando el assemble file"
+/usr/libexec/s2i/assemble
+rc=$?
+
+if [ $rc -eq 0 ]; then
+    echo "After successful assembling"
+				echo "Remove git"
+				yum remove git
+				echo "Install git"
+				yum install git
+else
+    echo "After failed assembling"
+fi
+
+exit $rc
